version: '3.8'

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.main:create_app
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
